# Generated by Django 6.0.5 on 2026-06-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miniblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="profiles/"
            ),
        ),
    ]
